image: archlinux
packages:
  - rustup
sources:
  - https://github.com/Austin-Ray/zian
secrets:
  - f1c8034f-2566-41bb-882c-a737fb07a0a9 # CodeCov token
environment:
  REPO: zian
  RUSTFLAGS: -Zinstrument-coverage
  LLVM_PROFILE_FILE: "zian-%p-%m.profraw"
tasks:
  - setup: |
      cd $REPO
      curl -L https://github.com/mozilla/grcov/releases/latest/download/grcov-linux-x86_64.tar.bz2 | tar jxf -
      rustup default nightly
      rustup component add llvm-tools-preview
  - build: |
      cd $REPO
      cargo build --verbose
  - test: |
      cd $REPO
      cargo test --verbose
      if [ -f ~/.code-cov ];
      then
        set +x
        source ~/.code-cov
        set -x
        ./grcov . --binary-path ./target/debug/ -s src/ -t lcov --branch --ignore-not-existing --ignore "/*" -o lcov.info
        export CI_BUILD_URL="$JOB_URL"
        export CI_BUILD_ID="$JOB_ID"
        export CI_JOB_ID="$JOB_ID"
        export VCS_BRANCH_NAME="${GITHUB_REF#refs/heads/}"
        export VCS_PULL_REQUEST="$GITHUB_PR_NUMBER"
        bash <(curl -s https://codecov.io/bash) -f lcov.info
      fi
  - qa: |
      cd $REPO
      cargo clippy -- -D warnings
